AWSTemplateFormatVersion: '2010-09-09'
Description: Hello World Lambda Function with S3 Trigger

Resources:
  HelloWorldLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorldLambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: sumith-dev
        S3Key: lambda_code.zip

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LogAndS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource: arn:aws:s3:::hello-world-lambda-bucket/*

Outputs:
  LambdaFunctionName:
    Value: !Ref HelloWorldLambda
    Description: Name of the Lambda function
