AWSTemplateFormatVersion: '2010-09-09'
Description: Create an SNS Topic

Parameters:
  TopicName:
    Type: String
    Description: The name of the SNS topic
    Default: sumith-topic
  DisplayName:
    Type: String
    Description: The display name for the SNS topic
    Default: Sumith's SNS Topic
  Subscription:
    Type: String
    Description: The email address to subscribe to the SNS topic
    Default: sumith.chandrashekhar@email.com
  KmsMasterKeyId:  # New parameter
    Type: String
    Description: The ID of the AWS KMS customer master key (CMK) to use for encrypting the SNS topic
    Default: ''  # Leave empty to use the default AWS-managed KMS keys


Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      DisplayName: !Ref DisplayName
      Subscription:
        - Endpoint: !Ref Subscription
          Protocol: email
      KmsMasterKeyId: !Ref KmsMasterKeyId  # New property

Outputs:
  TopicArn:
    Description: The ARN of the SNS topic
    Value: !Ref MyTopic
    Export:
      Name: !Sub '${AWS::StackName}-TopicArn'
  TopicName:
    Description: The name of the SNS topic
    Value: !Ref TopicName
    Export:
      Name: !Sub '${AWS::StackName}-TopicName'
