AWSTemplateFormatVersion: '2010-09-09'
Description: Create an SNS Topic

Parameters:
  TopicName:
    Type: String
    Description: The name of the SNS topic
    Default: sumith-topic
  DisplayName:
    Type: String
    Description: The display name for the SNS topic
    Default: Sumith's SNS Topic
  Subscription:
    Type: String
    Description: The email address to subscribe to the SNS topic
    Default: sumith.chandrashekhar@email.com

Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      DisplayName: !Ref DisplayName
      Subscription:
        - Endpoint: !Ref Subscription
          Protocol: email
      ContentBasedDeduplication: true

Outputs:
  TopicArn:
    Description: The ARN of the SNS topic
    Value: !Ref MyTopic
    Export:
      Name: !Sub '${AWS::StackName}-TopicArn'
  TopicName:
    Description: The name of the SNS topic
    Value: !Ref TopicName
    Export:
      Name: !Sub '${AWS::StackName}-TopicName'
