name: Run Template
on: [push]
jobs:
  CMS-Job:
    runs-on:
      - codebuild-cicd-cms-1-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      AWS_REGION: us-east-1
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Load Environment Variables
      run: |
        # Load environment-specific configuration
        source config/dev.env
        echo "S3_BUCKET_NAME: $S3_BUCKET_NAME"
      
    - name: List Files
      run: ls -R
      
    - name: Deploying CloudFormation Template
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/my-cloudformation-template.yml \
          --stack-name cms-cloudformation \
          --parameter-overrides TopicName=$TOPIC_NAME \
          --capabilities CAPABILITY_IAM

    - name: Check if Lambda Code exists in S3.
      run: |
        aws s3 ls s3://$S3_BUCKET_NAME/lambda_code.zip || touch_lambda_code=true

    - name: Touch Lambda Code
      if: ${{ env.touch_lambda_code == 'true' }}
      run: touch lambda_code.zip

    - name: Zip Lambda Code
      run: |
        cd lambda
        zip -r ../lambda_code.zip .
        cd ..

    - name: Upload lambda zip to S3
      run: aws s3 cp lambda_code.zip s3://${{ env.S3_BUCKET_NAME }}/lambda_code.zip

    - name: Deploying CloudFormation Lambda Templates
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/lambda-1.yml \
          --stack-name cms-lambda \
          --capabilities CAPABILITY_IAM

    - name: Update Lambda Function Code
      run: |
        aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --s3-bucket $S3_BUCKET_NAME \
          --s3-key lambda_code.zip
