name: Run Template
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-cicd-cms-1-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      AWS_REGION: us-east-1
      S3_BUCKET_NAME: sumith-dev
      LAMBDA_FUNCTION_NAME: HelloWorldLambda
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: List Files
      run: ls -R
    - name: Deploying CloudFormation Templates
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/my-cloudformation-template.yml \
          --stack-name my-stack \
          --parameter-overrides TopicName=my-new-topic \
          --capabilities CAPABILITY_IAM

    - name: Deploying CloudFormation Lambda Templates
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/lambda-1.yml \
          --stack-name cms-lambda \
          --capabilities CAPABILITY_IAM

    - name: Zip Lambda Code
      run: |
        cd lambda
        zip -r ../lambda_code.zip .
        cd ..

    - name: Upload lambda zip to S3
      run: aws s3 cp lambda_code.zip s3://${{ env.S3_BUCKET_NAME }}/

    - name: Update Lambda Function Code
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --s3-bucket ${{ env.S3_BUCKET_NAME }} \
          --s3-key lambda_code.zip
