name: Run Template
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-cicd-cms-1-${{ github.run_id }}-${{ github.run_attempt }}
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: List Files
      run: ls -R
    - name: Deploy CloudFormation Template
      run: |
        aws cloudformation deploy \
          --template-file ./my-cloudformation-template.yml \
          --stack-name my-stack \
          --parameter-overrides TopicName=my-new-topic \
          --capabilities CAPABILITY_IAM
